headers:
  Access-Control-Allow-Origin: "'*'"
  Access-Control-Allow-Credentials: "'true'"
  X-Content-Type-Options: "'nosniff'"
  X-XSS-Protection: "'1; mode=block'"
  X-Frame-Options: "'SAMEORIGIN'"
  Referrer-Policy: "'no-referrer-when-downgrade'"
  Strict-Transport-Security: "'max-age=31536000; includeSubDomains'"
template: ${file(config/serverless/response/response.vm)}
